# fly.toml app configuration file generated for artaeumbosstool on 2024-10-30T18:51:41-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'artaeum-raid-tool'
primary_region = 'sea'

[build]


[processes]
  worker = "npm start"


[[services]]
internal_port = 8080
processes = [ "worker" ]
protocol = "tcp"
  [services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[vm]]
  size = 'shared-cpu-1x'
